import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollableContainer: {
    paddingTop: 24,
    alignItems: 'center',
  },
  contentContainer: {
    backgroundColor: 'black',
    width: '100%',
    alignItems: 'center',
    paddingTop: 20,
    borderTopStartRadius: 30,
    borderTopEndRadius: 30,
    paddingBottom: 20
  },
  welcomeHeader: {
    marginBottom: 25,
    paddingVertical: 13,
    fontFamily: 'Tektur',
    alignItems: 'center',
  },
  welcomeText: {
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'Tektur',
    color: '#fff',
    marginBottom: 4,
  },
  welcomeSubtext: {
    fontSize: 16,
    color: '#ccc',
  },
  islandBox: {
    backgroundColor: 'rgba(35, 35, 35, 0.9)',
    borderColor: 'rgba(74, 144, 226, 0.18)',
    borderWidth: 1,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
    marginVertical: 17,
    width: '90%',
    aspectRatio: 1.5,
    overflow: 'hidden',
    padding: '5%',
  },
  islandTable: {
    backgroundColor: 'rgba(35, 35, 35, 0.9)',
    borderRadius: 30,
    marginVertical: 17,
    width: '90%',
    overflow: 'hidden',
  },
  extendedIslandTable: {
    backgroundColor: 'rgba(35, 35, 35, 0.92)',
    borderColor: 'rgba(74, 144, 226, 0.18)',
    borderWidth: 1,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
    marginVertical: 17,
    width: '90%',
    aspectRatio: 0.5,
    overflow: 'hidden'
  },
  cardHeader: {
    paddingHorizontal: 25,
    paddingVertical: 10,
    backgroundColor: 'rgba(74, 144, 226, 0.18)',
  },
  cardHeaderText: {
    fontSize: 20,
    fontFamily: 'Tektur-Head',
    color: 'white',
  },
  cardTableRow: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 13,
    borderBottomWidth: 1,
    width: '95%',
    borderBottomColor: 'white',
    alignSelf: 'center',
    flexDirection: 'row',
  },
  cardRowTextLeft: {
    fontSize: 15,
    fontFamily: 'Tektur-Sub',
    color: 'white',
    marginVertical: 2,
  },
  cardRowTextRight: {
    fontSize: 15,
    fontFamily: 'Tektur-Sub',
    marginVertical: 2,
    color: 'white',
    textAlign: 'right',
  },
  tablePayButton: {
    paddingVertical: 2,
    marginVertical: 2,
    width: '50%',
    height: '50%',
    backgroundColor: 'rgba(74, 144, 226, 0.18)',
    borderRadius: 8,
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  tablePayButtonText: {
    color: 'white',
    fontSize: 12,
    fontFamily: 'Tektur-Sub',
    textAlign: 'center',
  },
  transWelcomeHeader: {
    marginBottom: 15,
    alignItems: 'center',
  },
  transWelcomeText: {
    fontSize: 28,
    fontWeight: 'bold',
    fontFamily: 'Tektur',
    color: '#fff',
    marginBottom: 4,
    textAlign: 'center',
  },
  transWelcomeSubtext: {
    fontSize: 16,
    color: '#ccc',
    textAlign: 'center',
  },
  transactionCardForm: {
    backgroundColor: '#181818',
    width: '94%',
    alignItems: 'center',
    paddingTop: 26,
    paddingBottom: 38,
    marginBottom: 40,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderRadius: 36,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.13,
    shadowRadius: 32,
    elevation: 12,
  },
  transFieldBlock: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 16,
  },
  transTitle: {
    fontSize: 20,
    color: '#aad1fa',
    fontFamily: 'Tektur-Sub',
    margin: 10,
    paddingLeft: 8,
    textAlign: 'center',
  },
  transSubtitle: {
    fontSize: 14,
    color: 'white',
    fontFamily: 'Tektur-Sub',
    margin: 10,
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  transLabel: {
    fontSize: 16,
    color: '#aad1fa',
    fontFamily: 'Tektur-Sub',
    margin: 10,
    alignSelf: 'flex-start',
    paddingLeft: 8,
  },
  transInput: {
    backgroundColor: '#232323',
    borderWidth: 1,
    borderColor: 'rgba(74, 144, 226, 0.18)',
    borderRadius: 10,
    color: 'white',
    paddingHorizontal: 14,
    paddingVertical: 8,
    margin: 12,
    fontFamily: 'Tektur-Sub',
    fontSize: 16,
    width: 260,
  },
  transValue: {
    backgroundColor: '#232323',
    color: 'white',
    paddingHorizontal: 14,
    marginHorizontal: 12,
    fontFamily: 'Tektur-Sub',
    fontSize: 16,
    width: 260,
  },
  transPickerWrapper: {
    borderWidth: 1,
    borderColor: '#333',
    borderRadius: 10,
    backgroundColor: '#232323',
    width: 260,
    aspectRatio: 5,
    margin: 10,
    justifyContent: 'center',
  },
  transPickerInput: {
    color: 'white',
    fontSize: 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontFamily: 'Tektur'
  },
  transErrorText: {
    color: '#fa6d6d',
    fontSize: 13,
    marginBottom: 6,
  },
  checkbox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#232323',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(74, 144, 226, 0.18)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: 260,
  },
  transDateButton: {
    backgroundColor: '#222',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginTop: 6,
    marginBottom: 8,
    alignItems: 'center',
    width: 260,
  },
  transDateButtonText: {
    color: '#aad1fa',
    fontSize: 16,
    fontFamily: 'Tektur-Sub',
    textAlign: 'center',
  },
  transSubmitButton: {
    marginTop: 26,
    backgroundColor: '#5294ec',
    borderRadius: 13,
    paddingVertical: 12,
    paddingHorizontal: 44,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.11,
    shadowRadius: 9,
    elevation: 8,
  },
  transSubmitButtonText: {
    color: '#fff',
    fontFamily: 'Tektur-Head',
    fontSize: 17,
    textAlign: 'center',
  },
});

export const pickerStyles = {
  inputIOS: {
    color: 'white',
    fontSize: 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontFamily: 'Tektur', // Your font here!
  },
  inputAndroid: {
    color: 'white',
    fontSize: 16,
    paddingVertical: 8,
    paddingHorizontal: 10,
    fontFamily: 'Tektur', // May NOT work due to native spinner on Android
  },
  placeholder: {
    color: '#888',
    fontFamily: 'Tektur', // Supported on iOS
  },
};

export const modalStyles = StyleSheet.create({
  fabStyle: {
    position: 'absolute',
    right: 24,
    bottom: 32,
    backgroundColor: '#5294ec',
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    zIndex: 99,
  },
  menuBox: {
    backgroundColor: '#232323',
    borderRadius: 18,
    padding: 28,
    width: 340,
    maxWidth: '94%',
    maxHeight: 500,        // or tweak as desired
    shadowColor: '#222',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.15,
    shadowRadius: 14,
    elevation: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',  // Dims the background
    justifyContent: 'center',
    alignItems: 'center',
  },

});
